//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.29 at 03:37:50 AM EEST 
//


package org.example.bookstore;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.bookstore package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.bookstore
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBookResponse }
     * 
     */
    public GetBookResponse createGetBookResponse() {
        return new GetBookResponse();
    }

    /**
     * Create an instance of {@link BookWithRCType }
     * 
     */
    public BookWithRCType createBookWithRCType() {
        return new BookWithRCType();
    }

    /**
     * Create an instance of {@link GetBooksRequest }
     * 
     */
    public GetBooksRequest createGetBooksRequest() {
        return new GetBooksRequest();
    }

    /**
     * Create an instance of {@link AddBookResponse }
     * 
     */
    public AddBookResponse createAddBookResponse() {
        return new AddBookResponse();
    }

    /**
     * Create an instance of {@link GetBookReviewsRequest }
     * 
     */
    public GetBookReviewsRequest createGetBookReviewsRequest() {
        return new GetBookReviewsRequest();
    }

    /**
     * Create an instance of {@link AddReviewResponse }
     * 
     */
    public AddReviewResponse createAddReviewResponse() {
        return new AddReviewResponse();
    }

    /**
     * Create an instance of {@link PatchBookResponse }
     * 
     */
    public PatchBookResponse createPatchBookResponse() {
        return new PatchBookResponse();
    }

    /**
     * Create an instance of {@link GetBooksResponse }
     * 
     */
    public GetBooksResponse createGetBooksResponse() {
        return new GetBooksResponse();
    }

    /**
     * Create an instance of {@link BookFullType }
     * 
     */
    public BookFullType createBookFullType() {
        return new BookFullType();
    }

    /**
     * Create an instance of {@link DeleteBookResponse }
     * 
     */
    public DeleteBookResponse createDeleteBookResponse() {
        return new DeleteBookResponse();
    }

    /**
     * Create an instance of {@link UpdateBookResponse }
     * 
     */
    public UpdateBookResponse createUpdateBookResponse() {
        return new UpdateBookResponse();
    }

    /**
     * Create an instance of {@link DeleteBookRequest }
     * 
     */
    public DeleteBookRequest createDeleteBookRequest() {
        return new DeleteBookRequest();
    }

    /**
     * Create an instance of {@link PatchBookRequest }
     * 
     */
    public PatchBookRequest createPatchBookRequest() {
        return new PatchBookRequest();
    }

    /**
     * Create an instance of {@link BookOptionalType }
     * 
     */
    public BookOptionalType createBookOptionalType() {
        return new BookOptionalType();
    }

    /**
     * Create an instance of {@link AddBookRequest }
     * 
     */
    public AddBookRequest createAddBookRequest() {
        return new AddBookRequest();
    }

    /**
     * Create an instance of {@link BookType }
     * 
     */
    public BookType createBookType() {
        return new BookType();
    }

    /**
     * Create an instance of {@link UpdateBookRequest }
     * 
     */
    public UpdateBookRequest createUpdateBookRequest() {
        return new UpdateBookRequest();
    }

    /**
     * Create an instance of {@link GetBookRequest }
     * 
     */
    public GetBookRequest createGetBookRequest() {
        return new GetBookRequest();
    }

    /**
     * Create an instance of {@link GetBookReviewsResponse }
     * 
     */
    public GetBookReviewsResponse createGetBookReviewsResponse() {
        return new GetBookReviewsResponse();
    }

    /**
     * Create an instance of {@link ReviewType }
     * 
     */
    public ReviewType createReviewType() {
        return new ReviewType();
    }

    /**
     * Create an instance of {@link AddReviewRequest }
     * 
     */
    public AddReviewRequest createAddReviewRequest() {
        return new AddReviewRequest();
    }

}
